2017-03-13 10:35:01.777 [error] <0.179.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.184.0> exit with reason normal in context child_terminated
2017-03-13 10:36:04.143 [error] <0.223.0> gen_server list terminated with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 53
2017-03-13 10:36:04.143 [error] <0.223.0> CRASH REPORT Process list with 0 neighbours exited with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 53 in gen_server:terminate/7 line 812
2017-03-13 10:36:04.143 [error] <0.222.0> Supervisor {<0.222.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.221.0>) at <0.223.0> exit with reason no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 53 in context child_terminated
2017-03-13 10:39:31.046 [error] <0.108.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.113.0> exit with reason normal in context child_terminated
